version: '3'
services:
  web:
    image: httpd
    container_name: apache_web1
    restart: always
    expose:
      - "80"
    volumes:
      - ./www/:/usr/local/apache2/htdocs

    environment:
      VIRTUAL_HOST: website1

networks:
  default:
    external:
      name: nginx-proxy
